version: '3'

services:
  db:
    image: postgres:14.3
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - db-store:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=SCRAM-SHA-256$$4096:CN/srUQaTkDjUqDnvTraww==$$j0wE/Je5UkGvSTKTsAHO1cEc/KS3zIAN5xk8muV/otA=:ncrh96GBV7fiZOu+jbJuZHh1SL2pvRLNakbm+ACitqk=
      - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256 --auth-local=scram-sha-256
volumes:
  db-store:
