
spring:
  jpa:
    database: postgresql
  datasource:
    platform: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db/postgres
    username: postgres
    password: password
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

graphiql:
  mapping: /graphiql
  endpoint:
    graphql: /graphql
graphql:
  servlet:
    actuator-metrics: true

coome:
  assetS3BucketName: dev-coome-asset

